package tickable

import (
	"github.com/hunterjsb/xandaris/economy"
	"github.com/hunterjsb/xandaris/entities"
)

func init() {
	RegisterSystem(&CreditProductionSystem{
		BaseSystem: NewBaseSystem("CreditProduction", 10),
	})
}

// CreditProductionSystem handles credit production from planets.
//
// Credits come from three sources:
//  1. Population labor: base income from having citizens
//  2. Domestic economy: population consuming resources = economic activity
//  3. Trading Post revenue: share of galaxy trade volume
//
// This ensures self-sustaining colonies can cover their upkeep without
// needing external trade. Trade amplifies income, it doesn't gate it.
type CreditProductionSystem struct {
	*BaseSystem
	tickCounter int64
}

// Resource base prices for domestic economy valuation.
// These represent what citizens "pay" internally for goods — the economic
// activity generated by a functioning colony consuming resources.
var domesticPrices = map[string]float64{
	entities.ResWater:       8,  // basic necessity
	entities.ResIron:        5,  // infrastructure
	entities.ResOil:         12, // industrial
	entities.ResFuel:        15, // processed energy
	entities.ResRareMetals:  20, // advanced materials
	entities.ResHelium3:     18, // fusion fuel
	entities.ResElectronics: 40, // high-tech goods
}

func (cps *CreditProductionSystem) OnTick(tick int64) {
	if tick%10 != 0 {
		return
	}

	context := cps.GetContext()
	if context == nil {
		return
	}

	players := context.GetPlayers()

	var totalTradeVolume float64
	if me := context.GetGame().GetMarketEngine(); me != nil {
		totalTradeVolume = me.GetTradeVolume()
	}

	// Build player lookup by name
	playerMap := make(map[string]*entities.Player)
	for _, p := range players {
		if p != nil {
			playerMap[p.Name] = p
		}
	}

	// Use system entity planets (authoritative) instead of player.OwnedPlanets (stale)
	game := context.GetGame()
	if game == nil {
		return
	}
	for _, sys := range game.GetSystems() {
		for _, e := range sys.Entities {
			planet, ok := e.(*entities.Planet)
			if !ok || planet.Owner == "" || planet.Population <= 0 {
				continue
			}
			player := playerMap[planet.Owner]
			if player == nil {
				continue
			}

			productivityMult := planet.ProductivityBonus
			if productivityMult <= 0 {
				productivityMult = 1.0
			}
			techMult := 1.0 + planet.TechLevel*0.05

			// 1. Population labor: base income from citizens working.
			// Small colonies get a minimum income (administrative center generates value).
			// Scales: 1cr per 50 pop, minimum 10cr per inhabited planet.
			laborIncome := int(float64(planet.Population/50) * productivityMult * techMult)
			if laborIncome < 10 {
				laborIncome = 10 // minimum for any inhabited planet
			}

			// 2. Domestic economy: population demand generates credits.
			domesticIncome := 0
			for _, rate := range economy.PopulationConsumption {
				demand := float64(planet.Population) / rate.PopDivisor * rate.PerPopulation
				if demand < 0.5 {
					continue
				}
				stored := float64(planet.GetStoredAmount(rate.ResourceType))
				supplyRatio := 1.0
				if stored <= 0 {
					supplyRatio = 0.3
				}
				if price, ok := domesticPrices[rate.ResourceType]; ok {
					domesticIncome += int(demand * price * productivityMult * supplyRatio)
				}
			}

			// 2b. Resource diversity bonus
			typesStocked := 0
			for _, res := range []string{
				entities.ResWater, entities.ResIron, entities.ResOil,
				entities.ResFuel, entities.ResRareMetals, entities.ResHelium3,
				entities.ResElectronics,
			} {
				if planet.GetStoredAmount(res) > 0 {
					typesStocked++
				}
			}
			diversityMult := 1.0
			switch {
			case typesStocked >= 7:
				diversityMult = 3.0
			case typesStocked >= 5:
				diversityMult = 2.0
			case typesStocked >= 3:
				diversityMult = 1.5
			}
			domesticIncome = int(float64(domesticIncome) * diversityMult)

			// 3. Trading Post revenue: share of galaxy trade volume
			tpIncome := 0
			for _, be := range planet.Buildings {
				if b, ok := be.(*entities.Building); ok {
					if b.BuildingType == entities.BuildingTradingPost && b.IsOperational {
						tradeShare := int(totalTradeVolume * 0.01 * float64(b.Level))
						tpIncome += 2*b.Level + tradeShare
					}
				}
			}

			player.Credits += laborIncome + domesticIncome + tpIncome
		}
	}
}
